spring:
  #thymeleaf 설정
  thymeleaf:
    check-template-location: true
    prefix: classpath:/static/templates/   # .html 파일을 불러오기 위한 경로 설정(src/main/resources/templates)
    suffix: .html   # 파일 확장자
    cache: true

jasypt:
  encryptor:
    bean: jasyptEnc
    prefix: ENC(
    suffix: )